#ifndef OBJDB_FILTERS_GLOBAL_H
#define OBJDB_FILTERS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBJDB_FILTERS_LIBRARY)
#  define OBJDB_FILTERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OBJDB_FILTERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OBJDB_FILTERS_GLOBAL_H
